// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-c3KREkoBZaPD7qGVzvBcGyKcJ0tX5k',
    appId: '1:601753836357:web:38cc2a800ca38b90367c2c',
    messagingSenderId: '601753836357',
    projectId: 'todo-list-app-2cad9',
    authDomain: 'todo-list-app-2cad9.firebaseapp.com',
    storageBucket: 'todo-list-app-2cad9.firebasestorage.app',
    measurementId: 'G-0PW37B12VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXMKKu_xR88YiPjUlV3chvVgrcxb6iiY',
    appId: '1:601753836357:android:3834642b9a40dd96367c2c',
    messagingSenderId: '601753836357',
    projectId: 'todo-list-app-2cad9',
    storageBucket: 'todo-list-app-2cad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxtYrXOWW2iJDq1CFub55GvuReqDIRAI',
    appId: '1:601753836357:ios:dec5a21e61886b03367c2c',
    messagingSenderId: '601753836357',
    projectId: 'todo-list-app-2cad9',
    storageBucket: 'todo-list-app-2cad9.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxtYrXOWW2iJDq1CFub55GvuReqDIRAI',
    appId: '1:601753836357:ios:dec5a21e61886b03367c2c',
    messagingSenderId: '601753836357',
    projectId: 'todo-list-app-2cad9',
    storageBucket: 'todo-list-app-2cad9.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-c3KREkoBZaPD7qGVzvBcGyKcJ0tX5k',
    appId: '1:601753836357:web:20c96c9dc22f79a6367c2c',
    messagingSenderId: '601753836357',
    projectId: 'todo-list-app-2cad9',
    authDomain: 'todo-list-app-2cad9.firebaseapp.com',
    storageBucket: 'todo-list-app-2cad9.firebasestorage.app',
    measurementId: 'G-2BGX9YC53J',
  );
}
